### ISSUE TITLE
mockUp

### ISSUE THREAD

**Issue by sreyleakel** [PNC-WEP-ONE-WEEK-PROJECT/PHP-DB-G10#13]
design interface

**Comment by sreyneven** [comment]
![image](https://user-images.githubusercontent.com/90229523/158730565-e8da828b-1e58-4ba0-a834-10b4fd4a4778.png)
![image](https://user-images.githubusercontent.com/90229523/158730596-f2e4f0b3-7c55-42bd-b590-d427962b0683.png)
![image](https://user-images.githubusercontent.com/90229523/158730624-5ccf71b5-3edf-4163-8259-bd433f796fd0.png)
![image](https://user-images.githubusercontent.com/90229523/158730644-d463b464-486a-46e4-9b3d-7648734e8a1d.png)
![image](https://user-images.githubusercontent.com/90229523/158730655-1bee12ab-c7be-4fd5-9782-caa385c26a6a.png)
![image](https://user-images.githubusercontent.com/90229523/158730667-dda039ce-c422-4793-a97f-7675d1ab3480.png)
